/**
 * `rn-devtools-hub init`: zero-effort integration codemod.
 *
 * Detects the project shape (Expo or bare React Native, entry point,
 * TypeScript) and which libraries are installed, generates a glue file
 * wired to exactly those libraries, and hooks it into the entry point
 * behind a __DEV__ guard.
 *
 * Idempotent and reversible: it never overwrites without --force and
 * prints every file it touches. Zero dependencies (node:fs only).
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const GLUE_MARKER = "rn-devtools-hub";

const readJson = (path) => {
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return null;
  }
};

/** What the project has, so we only generate code that will actually run */
const detectProject = (root) => {
  const pkg = readJson(join(root, "package.json"));
  if (!pkg) return null;

  const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
  const has = (name) => Object.prototype.hasOwnProperty.call(deps, name);

  const typescript = existsSync(join(root, "tsconfig.json"));
  const expoRouter = has("expo-router");
  const entryFromPkg = pkg.main ?? "";

  // Where do we hook the guarded require?
  // - Expo Router: no user entry by default, we create index.js and point
  //   package.json main at it (the documented Expo custom-entry pattern)
  // - Otherwise: the existing index.js / index.ts
  let entryFile = null;
  let entryStrategy = null;
  if (entryFromPkg.includes("expo-router/entry")) {
    entryFile = "index.js";
    entryStrategy = existsSync(join(root, "index.js")) ? "prepend" : "create-expo-router";
  } else {
    for (const candidate of ["index.js", "index.ts", "index.tsx", "App.js", "App.tsx"]) {
      if (existsSync(join(root, candidate))) {
        entryFile = candidate;
        entryStrategy = "prepend";
        break;
      }
    }
  }

  return {
    pkg,
    typescript,
    entryFile,
    entryStrategy,
    isExpo: has("expo"),
    features: {
      constants: has("expo-constants"),
      axios: has("axios"),
      reactQuery: has("@tanstack/react-query"),
      asyncStorage: has("@react-native-async-storage/async-storage"),
      sqlite: has("expo-sqlite"),
      router: expoRouter,
      device: has("expo-device"),
      application: has("expo-application"),
      network: has("expo-network"),
      viewShot: has("react-native-view-shot"),
      installed: has("rn-devtools-hub"),
    },
  };
};

/** Generates a glue file containing only what the project can support */
const generateGlue = (project) => {
  const f = project.features;
  const ts = project.typescript;
  const lines = [];

  lines.push("/**");
  lines.push(" * rn-devtools-hub: development inspector wiring.");
  lines.push(" * Generated by `npx rn-devtools-hub init`. Safe to edit.");
  lines.push(" *");
  lines.push(" * Nothing here runs in production: the entry point requires this");
  lines.push(" * file behind __DEV__, and the SDK checks __DEV__ as well.");
  lines.push(" */");
  lines.push(`import { devtools } from "rn-devtools-hub/client";`);

  if (f.constants) lines.push(`import Constants from "expo-constants";`);
  if (f.axios) lines.push(`import axios from "axios";`);
  if (f.asyncStorage) lines.push(`import AsyncStorage from "@react-native-async-storage/async-storage";`);
  if (f.device) lines.push(`import * as Device from "expo-device";`);
  if (f.application) lines.push(`import * as Application from "expo-application";`);
  if (f.network) lines.push(`import * as Network from "expo-network";`);
  lines.push(`import { DevSettings, Platform } from "react-native";`);
  lines.push("");

  lines.push("// Hub address: same machine as the Metro bundler.");
  if (f.constants) {
    lines.push("const host =");
    lines.push(`  Constants.expoConfig?.hostUri?.split(":")[0] ??`);
    lines.push(`  (Constants${ts ? " as any" : ""}).manifest2?.extra?.expoGo?.debuggerHost?.split(":")[0] ??`);
    lines.push(`  "localhost";`);
  } else {
    lines.push("// Without expo-constants we cannot detect Metro's IP:");
    lines.push("// replace with your dev machine IP, or set it via an env var.");
    lines.push(`const host = "localhost";`);
  }
  lines.push("");

  lines.push("devtools.init({");
  lines.push("  serverUrl: `ws://${host}:8973`,");
  lines.push(`  appName: ${JSON.stringify(project.pkg.name ?? "app")},`);
  if (f.device) {
    lines.push("  deviceName: Device.deviceName ?? Device.modelName ?? Platform.OS,");
    lines.push("  // Stable id: reloads reconnect as the same device, no ghost sessions");
    lines.push("  stableId: [Device.modelName, Device.osBuildId, Platform.OS]");
    lines.push(`    .filter(Boolean).join("-").replace(/[^a-zA-Z0-9_-]/g, "").slice(0, 40),`);
  } else {
    lines.push("  deviceName: Platform.OS,");
  }
  lines.push("});");
  lines.push("");

  lines.push("// Dependency-free panels");
  lines.push("devtools.attachConsole();");
  lines.push("devtools.attachCrashReporting();");
  lines.push("devtools.startPerformanceSampler();");
  lines.push("");

  if (f.axios) {
    lines.push("// Network panel: the global axios instance.");
    lines.push("// If your app uses a custom instance, attach it too:");
    lines.push('//   devtools.attachAxios(myApiInstance, "api");');
    lines.push(`devtools.attachAxios(axios, "axios");`);
    lines.push("");
  }

  if (f.device || f.application) {
    lines.push("// Device and app identity (shown in the Overview and bug reports)");
    lines.push("devtools.emit(\"app.info\", {");
    lines.push(`  appName: ${JSON.stringify(project.pkg.name ?? "app")},`);
    if (f.application) {
      lines.push("  appVersion: Application.nativeApplicationVersion,");
      lines.push("  buildVersion: Application.nativeBuildVersion,");
    }
    lines.push("  platform: Platform.OS,");
    if (f.device) {
      lines.push("  osName: Device.osName,");
      lines.push("  osVersion: Device.osVersion,");
      lines.push("  modelName: Device.modelName,");
      lines.push("  brand: Device.brand,");
      lines.push("  deviceName: Device.deviceName,");
      lines.push("  totalMemoryMb: Device.totalMemory");
      lines.push("    ? Math.round(Device.totalMemory / (1024 * 1024))");
      lines.push("    : null,");
      lines.push("  isDevice: Device.isDevice,");
    }
    lines.push(`  jsEngine: (globalThis${ts ? " as any" : ""})?.HermesInternal ? "hermes" : "jsc",`);
    if (f.constants) {
      lines.push("  devMode:");
      lines.push(`    String(Constants.executionEnvironment) === "storeClient"`);
      lines.push(`      ? "Expo Go"`);
      lines.push(`      : "Development build",`);
      lines.push(`  nativeCapable: String(Constants.executionEnvironment) !== "storeClient",`);
    }
    lines.push("});");
    lines.push("");
  }

  if (f.network) {
    lines.push("// Connection tile: Wi-Fi or cellular, IP address");
    lines.push("const emitNetworkInfo = async () => {");
    lines.push("  try {");
    lines.push("    const state = await Network.getNetworkStateAsync();");
    lines.push(`    devtools.emit("net.info", {`);
    lines.push("      type: state.type,");
    lines.push("      isConnected: state.isConnected,");
    lines.push("      isInternetReachable: state.isInternetReachable,");
    lines.push("      ipAddress: await Network.getIpAddressAsync().catch(() => null),");
    lines.push("    });");
    lines.push("  } catch {");
    lines.push("    // network info unavailable");
    lines.push("  }");
    lines.push("};");
    lines.push("emitNetworkInfo();");
    lines.push("setInterval(emitNetworkInfo, 15000);");
    lines.push("");
  }

  if (f.asyncStorage) {
    lines.push("// Storage panel: list keys, read values, and track writes");
    lines.push("// (AsyncStorage does not record write times, so we intercept them)");
    lines.push(`const writeTimes = new Map${ts ? "<string, number>" : ""}();`);
    lines.push("const originalSetItem = AsyncStorage.setItem.bind(AsyncStorage);");
    lines.push(`(AsyncStorage${ts ? " as any" : ""}).setItem = async (key${ts ? ": string" : ""}, value${ts ? ": string" : ""}, ...rest${ts ? ": any[]" : ""}) => {`);
    lines.push("  const result = await originalSetItem(key, value, ...rest);");
    lines.push("  writeTimes.set(key, Date.now());");
    lines.push(`  devtools.emit("storage.write", {`);
    lines.push(`    op: "set", key, size: value?.length ?? 0,`);
    lines.push("    preview: String(value ?? \"\").slice(0, 120),");
    lines.push("  });");
    lines.push("  return result;");
    lines.push("};");
    lines.push("");
    lines.push(`devtools.onCommand("storage.keys", async () => {`);
    lines.push("  const keys = await AsyncStorage.getAllKeys();");
    lines.push("  const pairs = await AsyncStorage.multiGet([...keys]);");
    lines.push("  return {");
    lines.push("    keys: pairs.map(([key, value]) => ({");
    lines.push("      key,");
    lines.push("      size: value?.length ?? 0,");
    lines.push("      lastWriteAt: writeTimes.get(key) ?? null,");
    lines.push("    })),");
    lines.push("  };");
    lines.push("});");
    lines.push(`devtools.onCommand("storage.get", async (payload${ts ? ": any" : ""}) => {`);
    lines.push(`  const key = String((payload${ts ? " as any" : ""})?.key ?? "");`);
    lines.push("  const value = await AsyncStorage.getItem(key);");
    lines.push("  try {");
    lines.push("    return { key, size: value?.length ?? 0, value: value ? JSON.parse(value) : value };");
    lines.push("  } catch {");
    lines.push("    return { key, size: value?.length ?? 0, value };");
    lines.push("  }");
    lines.push("});");
    lines.push("");
  }

  if (f.sqlite) {
    lines.push("// SQLite console (read-only). Point this at YOUR database:");
    lines.push("// import { db } from \"./your-database\";");
    lines.push(`// devtools.onCommand("sqlite.query", async (payload) => {`);
    lines.push(`//   const sql = String((payload${ts ? " as any" : ""})?.sql ?? "");`);
    lines.push(`//   if (!/^\\s*(select|pragma)\\b/i.test(sql)) {`);
    lines.push(`//     throw new Error("Read-only: SELECT or PRAGMA only");`);
    lines.push("//   }");
    lines.push("//   return { rows: await db.getAllAsync(sql) };");
    lines.push("// });");
    lines.push("");
  }

  lines.push("// Actions panel: buttons shown in the dashboard");
  lines.push(`devtools.registerAction({ name: "reload", label: "Reload the app" }, () => {`);
  lines.push("  setTimeout(() => DevSettings.reload(), 300);");
  lines.push("  return { ok: true };");
  lines.push("});");
  if (f.asyncStorage) {
    lines.push("devtools.registerAction(");
    lines.push(`  { name: "clear-storage", label: "Clear AsyncStorage", danger: true },`);
    lines.push("  async () => {");
    lines.push("    await AsyncStorage.clear();");
    lines.push("    return { ok: true };");
    lines.push("  }");
    lines.push(");");
  }
  lines.push("");

  if (f.viewShot) {
    lines.push("// Mirror: live screen stream from inside the app");
    lines.push(`let captureScreen${ts ? ": ((options: any) => Promise<string>) | null" : ""} = null;`);
    lines.push("try {");
    lines.push(`  captureScreen = require("react-native-view-shot").captureScreen;`);
    lines.push("} catch {");
    lines.push("  // react-native-view-shot not available");
    lines.push("}");
    lines.push(`let streamTimer${ts ? ": ReturnType<typeof setInterval> | null" : ""} = null;`);
    lines.push(`devtools.onCommand("screen.capture", async () => {`);
    lines.push(`  if (!captureScreen) throw new Error("react-native-view-shot not installed");`);
    lines.push(`  return { format: "jpg", base64: await captureScreen({ format: "jpg", quality: 0.6, result: "base64" }) };`);
    lines.push("});");
    lines.push(`devtools.onCommand("screen.stream.start", (payload${ts ? ": any" : ""}) => {`);
    lines.push(`  if (!captureScreen) throw new Error("react-native-view-shot not installed");`);
    lines.push(`  const fps = Math.min(Math.max(Number((payload${ts ? " as any" : ""})?.fps) || 2, 1), 5);`);
    lines.push("  if (streamTimer) clearInterval(streamTimer);");
    lines.push("  streamTimer = setInterval(async () => {");
    lines.push("    try {");
    lines.push(`      const base64 = await captureScreen({ format: "jpg", quality: 0.4, result: "base64" });`);
    lines.push(`      devtools.emitRaw("screen.frame", { format: "jpg", base64 });`);
    lines.push("    } catch {");
    lines.push("      // frame skipped (secure screen, system modal)");
    lines.push("    }");
    lines.push("  }, Math.round(1000 / fps));");
    lines.push("  setTimeout(() => { if (streamTimer) clearInterval(streamTimer); }, 5 * 60 * 1000);");
    lines.push("  return { ok: true, fps };");
    lines.push("});");
    lines.push(`devtools.onCommand("screen.stream.stop", () => {`);
    lines.push("  if (streamTimer) clearInterval(streamTimer);");
    lines.push("  return { ok: true };");
    lines.push("});");
    lines.push(`devtools.emit("capabilities", { viewShotAvailable: !!captureScreen });`);
    lines.push("");
  }

  if (f.reactQuery) {
    lines.push("// React Query cache panel: needs YOUR queryClient instance.");
    lines.push("// Call this once from where the client is created:");
    lines.push("//   import { attachQueryClient } from \"./devtools.setup\";");
    lines.push("//   if (__DEV__) attachQueryClient(queryClient);");
    lines.push(`export function attachQueryClient(queryClient${ts ? ": any" : ""}) {`);
    lines.push("  const snapshot = () => ({");
    lines.push(`    queries: queryClient.getQueryCache().getAll().map((query${ts ? ": any" : ""}) => ({`);
    lines.push("      queryKey: query.queryKey,");
    lines.push("      status: query.state.status,");
    lines.push("      isStale: query.isStale(),");
    lines.push("      observers: query.getObserversCount(),");
    lines.push("      dataUpdatedAt: query.state.dataUpdatedAt,");
    lines.push("      data: query.state.data,");
    lines.push("    })),");
    lines.push("  });");
    lines.push(`  devtools.onCommand("query.snapshot", snapshot);`);
    lines.push("  devtools.registerAction(");
    lines.push(`    { name: "invalidate-queries", label: "Invalidate React Query cache" },`);
    lines.push("    () => {");
    lines.push("      queryClient.invalidateQueries();");
    lines.push("      return { ok: true };");
    lines.push("    }");
    lines.push("  );");
    lines.push("}");
    lines.push("");
  }

  if (f.router) {
    lines.push("// Screens panel: mount this hook once in your root layout");
    lines.push("//   import { useDevtoolsNavigation } from \"../devtools.setup\";");
    lines.push("//   useDevtoolsNavigation();");
    lines.push("export function useDevtoolsNavigation() {");
    lines.push(`  const { usePathname } = require("expo-router");`);
    lines.push(`  const { useEffect, useRef } = require("react");`);
    lines.push("  const pathname = usePathname();");
    lines.push(`  const previous = useRef(null);`);
    lines.push("  useEffect(() => {");
    lines.push("    if (!devtools.enabled) return;");
    lines.push(`    devtools.emit("nav.screen", {`);
    lines.push("      screen: pathname,");
    lines.push("      previousScreen: previous.current?.screen,");
    lines.push("      previousDurationMs: previous.current");
    lines.push("        ? Date.now() - previous.current.since");
    lines.push("        : undefined,");
    lines.push("    });");
    lines.push("    previous.current = { screen: pathname, since: Date.now() };");
    lines.push("  }, [pathname]);");
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
};

const ENTRY_SNIPPET = (gluePath) => `// rn-devtools-hub: development inspector (stripped from production builds)
if (__DEV__) {
  require("${gluePath}");
}
`;

export const runInit = (argv, root = process.cwd()) => {
  const dryRun = argv.includes("--dry-run");
  const force = argv.includes("--force");

  const project = detectProject(root);
  if (!project) {
    console.error("rn-devtools-hub init: no package.json found in " + root);
    console.error("Run this from the root of your React Native project.");
    return 1;
  }

  const detected = Object.entries(project.features)
    .filter(([key, value]) => value && key !== "installed")
    .map(([key]) => key);

  console.log("");
  console.log("  rn-devtools-hub init");
  console.log("  --------------------");
  console.log(`  Project      : ${project.pkg.name ?? "(unnamed)"}${project.isExpo ? " (Expo)" : ""}`);
  console.log(`  Language     : ${project.typescript ? "TypeScript" : "JavaScript"}`);
  console.log(`  Entry point  : ${project.entryFile ?? "not found"}`);
  console.log(`  Integrations : ${detected.length ? detected.join(", ") : "core only"}`);
  console.log("");

  const glueName = project.typescript ? "devtools.setup.ts" : "devtools.setup.js";
  const gluePath = join(root, glueName);
  const writes = [];

  // All package.json edits go through this single object, written once
  const pkgPath = join(root, "package.json");
  const pkgEdit = readJson(pkgPath);
  let pkgChanged = false;

  // `npm run devtools` starts the hub with the project's own package manager
  if (pkgEdit) {
    pkgEdit.scripts = pkgEdit.scripts ?? {};
    if (!pkgEdit.scripts.devtools) {
      pkgEdit.scripts.devtools = "rn-devtools-hub";
      pkgChanged = true;
    }
  }

  if (existsSync(gluePath) && !force) {
    console.log(`  ${glueName} already exists, keeping it (use --force to regenerate)`);
  } else {
    writes.push([gluePath, generateGlue(project)]);
  }

  // Wire the entry point
  if (!project.entryFile) {
    console.log("  No entry point found: add this yourself in your entry file:");
    console.log("");
    console.log(ENTRY_SNIPPET(`./${glueName.replace(/\.(ts|js)$/, "")}`));
  } else {
    const entryPath = join(root, project.entryFile);
    const relativeGlue = `./${glueName.replace(/\.(ts|js)$/, "")}`;

    if (project.entryStrategy === "create-expo-router") {
      // Expo Router has no user entry: create one that keeps the router entry
      writes.push([
        entryPath,
        `${ENTRY_SNIPPET(relativeGlue)}\n// Expo Router entry point (must stay last)\nimport "expo-router/entry";\n`,
      ]);
      if (pkgEdit && pkgEdit.main !== "index.js") {
        pkgEdit.main = "index.js";
        pkgChanged = true;
      }
    } else {
      const current = readFileSync(entryPath, "utf-8");
      if (current.includes(GLUE_MARKER)) {
        console.log(`  ${project.entryFile} already wired, skipping`);
      } else {
        writes.push([entryPath, `${ENTRY_SNIPPET(relativeGlue)}\n${current}`]);
      }
    }
  }

  if (pkgChanged) {
    writes.push([pkgPath, JSON.stringify(pkgEdit, null, 2) + "\n"]);
  }

  if (dryRun) {
    console.log("  Dry run, nothing written. Files that would change:");
    writes.forEach(([path]) => console.log(`    ${path.slice(root.length + 1)}`));
    console.log("");
    return 0;
  }

  for (const [path, content] of writes) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, "utf-8");
    console.log(`  written: ${path.slice(root.length + 1)}`);
  }

  console.log("");
  console.log("  Next steps:");
  if (!project.features.installed) {
    console.log("    1. npm install --save-dev rn-devtools-hub");
    console.log("    2. npm run devtools             (start the hub)");
  } else {
    console.log("    1. npm run devtools             (start the hub)");
  }
  console.log("    Open the printed URL, then start your app in dev mode.");
  if (project.features.reactQuery) {
    console.log("");
    console.log("  Optional: call attachQueryClient(queryClient) where you create");
    console.log("  your React Query client, to enable the Cache panel.");
  }
  if (project.features.router) {
    console.log("  Optional: call useDevtoolsNavigation() in your root layout");
    console.log("  to enable the Screens panel.");
  }
  if (!project.features.viewShot) {
    console.log("");
    console.log("  Tip: npx expo install react-native-view-shot enables the live");
    console.log("  app screen mirror (works in Expo Go, no native build needed).");
  }
  console.log("");
  return 0;
};
